### ISSUE TITLE
YAML support, Directory Support and compound syntax

### ISSUE THREAD

**Issue by ntrp** [simplesteph/kafka-security-manager#71]
Hi, as part of a project we implemented support for YAML format and multi-file support. The YAML support allows to write a more human readable permission config:
```
users:
  C=DE,O=org,OU=WEB,CN=t1.example.com,L=Stuttgart,ST=reg:
    topics:
      Topic1:
       - Read
      TopicPref_*:
        - All
    groups:
      team1-app1-*:
        - Read
        - Describe
```
In the YAML example you can also see the compound syntax where you define `All` to give all permissions on a topic.

The multi-file support allows to organize the permissions in different files to make separation of concerns more easy.

The implementation was done around version 0.5 so I would need to invest some time to create a valid pull request, are you interested in merging this kind of features? Otherwise I will spare the time ^^'
